recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: ollama_llm
  flow_retrieval:
      active: false
policies:
- name: FlowPolicy
# - name: IntentlessPolicy
assistant_id: 20250320-215119-randomized-golf
